version: "3.5"

networks:
  appnet-phalcon:
    name: php-phalcon
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.112.0.0/24

services:
  api-php-phalcon:
    build: ./.docker/apache
    volumes:
      - ./api:/usr/src/app
    ports:
      - "80:80"
    links:
      - db-php-phalcon
    restart:
      on-failure
    networks:
      appnet-phalcon:
        ipv4_address: "172.112.0.2"

  db-php-phalcon:
    image: mysql:5.7
    env_file:
      - ./.docker/mysql/.env
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    expose:
      - 3306
    restart:
      on-failure
    networks:
      appnet-phalcon:
        ipv4_address: "172.112.0.3"